### PR TITLE
Vet clinic database: query and update animals table

### PR DESCRIPTION
**Pull request by Yidnekachew-cmd**
### In this branch, I have added the following;

- [ ] Add a column species of type string to the `animals` table. And modify the schema.sql file.
- [ ] Insert the given data and add those insertions to the data.sql file.
- [ ] Inside a transaction update the `animals` table by setting the species column to unspecified. And verify that the change was made. Then roll back the change and verify that the species columns went back to the state before the transaction.
- [ ] Inside a transaction:
    - Update the `animals` table by setting the species column to `digimon` for all animals that have a name ending in `mon.`
    - Update the `animals` table by setting the species column to `pokemon` for all animals that don't have species already set.
    - Verify that changes were made.
    - Commit the transaction.
    - Verify that changes persist after committing.
- [ ] Screenshot of the results of the actions.

Screenshot from 2023-05-09 20-25-10

- [ ] Inside a transaction delete all records in the `animals` table, then roll back the transaction. After the rollback verify that if all records in the animals table still exist.
- [ ] Screenshot of the results of the actions.

Screenshot from 2023-05-09 20-30-14

- [ ] Inside a transaction:
    - Delete all animals born after Jan 1st, 2022.
    - Create a savepoint for the transaction.
    - Update all animals' weight to be their weight multiplied by -1.
    - Rollback to the savepoint
    - Update all animals' weights that are negative to be their weight multiplied by -1.
    - Commit transaction
- [ ] Add all these transactions to the queries.sql file.
- [ ] Screenshot of the results of the actions.

Screenshot from 2023-05-09 21-04-55

- [ ] Write queries to answer the following questions:
    - How many animals are there?
    - How many animals have never tried to escape?
    - What is the average weight of animals?
    - Who escapes the most, neutered or not neutered animals?
    - What is the minimum and maximum weight of each type of animal?
    - What is the average number of escape attempts per animal type of those born between 1990 and 2000?
- [ ]  Add these queries to the queries.sql file.
- [ ] Screenshot of the results of the actions.

Screenshot from 2023-05-09 21-35-24

Screenshot from 2023-05-09 21-37-02

### CODE REVIEW

**Review by brainconnect93 — CHANGES_REQUESTED** [review]
### Hi @Yidnekachew-cmd, 👋 

# STATUS: Changes Required :recycle:

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



### To Highlight :1st_place_medal: 

-  Has a proper Pull Request. ✔️  
- query and update the animal's table perfectly ✔️
- Add a Screenshot of all queries to the PR ✔️
- Good use of Git flow ✔️ 

### Changes Required

- [x] I would kindly suggest you work on the MIT license link as the link is currently broken. This is simply because the License file is missing in your project root directory.  Kindly add it and be sure you are targeting it correctly in your Readme file.

MIT :point_down: 

Screenshot_20230509_205742


- [x]  _Please check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me on( @brainconnect93 ) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yidnekachew-cmd** [comment]
Hi @brainconnect93, Thank you! :hugs:

**Review by abdulhamiid — APPROVED** [review]
# :green_circle:  Approved! :partying_face:
Hi @Yidnekachew-cmd 👋, 
image
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights 🌟

- ✔️ Descriptions are very descriptive
- ✔️ Use GitFlow
- ✔️ Meaningful commit messages.
- ✔️ Use SQL commands

## Optional suggestions 🤷‍♂️
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

## Important Notes 📝
- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Yidnekachew-cmd** [comment]
Hi @abdulhamiid, Thank You!

**Pull request merged**
